theme: jekyll-theme-tactile

title: Jean-Paul Ampuero
author: Jean-Paul Ampuero
email: ampuero@geoazur.unice.fr
description: > # this means to ignore newlines until "baseurl:"
  Seismology + Earthquake Dynamics + Rupture Imaging

# social links
twitter_username: DocTerremoto # DO NOT include the @ character, or else the build will fail!
github_username:  jpampuero # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
